### ISSUE TITLE
Bug in USB causes host ports to sometimes fail to activate

### ISSUE THREAD

**Issue by lbdroid** [HiKey960-Car/HiKey960-Car#26]
https://bugs.96boards.org/show_bug.cgi?id=662

This is a show stopper, since we absolutely depend on USB host working.
Reverting one commit that doesn't look related on the surface makes it seem like the issue occurs much less frequently, but it still does occasionally happen.

The only (temporary, hack) solution I can see at this point until upstream gets it figured out, is to check the status of the USB host on bootup, and reboot if it is not working correctly.

Failure:

cat /sys/devices/platform/soc/ff200000.hisi_usb/plugusb
current state: USB_STATE_OFF
 usage: echo hoston/hostoff/deviceon/deviceoff > plugusb

Success:

cat /sys/devices/platform/soc/ff200000.hisi_usb/plugusb
current state: USB_STATE_HOST
 usage: echo hoston/hostoff/deviceon/deviceoff > plugusb

**Comment by lbdroid** [comment]
Temporary workaround for this problem;
https://github.com/HiKey960-Car/android_kernel_linaro_hikey/commit/7cae63a2ee393f1bbc7fb0db6135ca1539f01cd2

This disables USB device mode.

**Comment by ASerbinski** [comment]
Workaround is no longer suitable, with recent kernel changes, it causes more problems than it solves. In addition, I believe that upstream kernel may have solved this issue.
