### ISSUE TITLE
Failed to compile AOSP 9 (master)

### ISSUE THREAD

**Issue by kryszpaw** [HiKey960-Car/HiKey960-Car#30]
I wanted to build AOSP 9  Automotive/Car for HiKey960 board.
I'm following guide here. I'm using AOSP master from today (18.09.2018). 
I have replaced /device/linaro/hikey with repo attached here (**android_device_linaro_hikey**).
I haven't apply patches (they don't seem to fix my problem anyway).

> source ./build/envsetup.sh
> lunch hikey960_car-userdebug
> make -j4

and after a while I got:

> [ 53% 455/857] including system/sepolicy/Android.mk ...
> system/sepolicy/Android.mk:79: warning: BOARD_SEPOLICY_VERS not specified, assuming current platform version
> [100% 857/857] writing build rules ...
> FAILED:
> build/make/core/base_rules.mk:305: error: overriding commands for target `out/target/product/hikey960/obj/lib/android.hardware.renderscript@1.0-impl.so', previously defined at build/make/core/base_rules.mk:305

p.s. previously I got other problem solved by removing **broadcastradio**.

> FAILED: out/soong/build.ninja
> out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
> error: device/linaro/hikey/broadcastradio/Android.bp:17:1: "android.hardware.broadcastradio@1.1-service.dmhd1000" depends on undefined module "android.hardware.broadcastradio@1.1-utils-lib"

I know this project was last updated in April, not sure what AOSP was used here, but with current AOSP master it doesn't work.

**Please help...**

**Comment by ASerbinski** [comment]
This repository is deprecated
